package com.translator.token;

public enum TokenType {
    IDENTIFIER,
    NUMBER,
    STRING,
    CHAR_LITERAL,

    INT, LONG, SHORT, CHAR, FLOAT, DOUBLE, VOID, BOOL, STRUCT, TYPEDEF, ENUM, UNION, NULL, SIZEOF, STATIC, SIZE_T, CONST, UNSIGNED,
    DEFINE,

    IF, ELSE, WHILE, FOR, DO, SWITCH, CASE, DEFAULT, BREAK, CONTINUE, RETURN,

    PLUS, MINUS, MUL, DIV, MOD,
    ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MUL_ASSIGN, DIV_ASSIGN, MOD_ASSIGN,
    BIT_AND_ASSIGN, BIT_OR_ASSIGN, BIT_XOR_ASSIGN, SHL_ASSIGN, SHR_ASSIGN,
    INC, DEC,
    EQ, NEQ, LT, GT, LE, GE,
    AND, OR, NOT,
    BIT_AND, BIT_OR, BIT_XOR, BIT_NOT,
    SHL, SHR,

    LPAREN, RPAREN,
    LBRACE, RBRACE,
    LBRACKET, RBRACKET,
    SEMICOLON, COMMA, DOT, COLON, QUESTION, STRUCT_ACCESS,

    EOF
}